name: wayl_soft_manager
description: Wayl Soft MikroTik Manager Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  routeros_api: ^1.1.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  printing: ^5.11.1
  intl: ^0.19.0

flutter:
  uses-material-design: true
